

name: CI

on:
  push:
    branches: [ master ]
  


  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

     
    steps:
      - uses: actions/checkout@v2
         #copy file dist
       
      - name: Setup Node.js environment 
        uses: actions/setup-node@v2.1.5
        with:
        
          node-version: 14.x
           #install dependencies
      - name: Instal dependencies
        run: yarn
          #execute build
      - name: Run build
        run: uarn build

      
      
    
    
      
      
      #substitut code existent in dist new code
      #execute yarn i na DO
      #execute migrations TypeORM
      #restart serve node
      


